#!/bin/bash

# A simple script to display wifi and ethernet name
# 'ssid -i' = with icon, 'ssid' = text only
# By AkemiKami201

WIFI_SSID=$(/sbin/iwgetid -r) # WiFi network name, if connected
ETH_INTERFACE=$(ip link | grep -oP 'en\w+') # detect ethernet interfaces

# Check if there is an IP assigned to the Ethernet interface
ETH_IP=$(ip -o -4 addr show dev ${ETH_INTERFACE} | awk '{print $4}' | cut -d/ -f1)

# if you are connected to WiFi
if [[ "${WIFI_SSID}" != "" ]]; then
	if  [[ $1 = "-i" ]]; then
    	echo "  ${WIFI_SSID}"
	else
    	echo "${WIFI_SSID}"
	fi
# if connected via Ethernet
elif [[ "$ETH_IP" != "" ]]; then
	if [[ $1 = "-i" ]]; then
		echo " ${ETH_INTERFACE}"
	else
		echo "${ETH_INTERFACE}"
	fi
else
	# if there is no connection
	echo "None"
fi

exit
